version: '3'

services:
  node-ts:
    image: mysql:8.0.22
    container_name: node-ts
    restart: "no"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: mapeamento
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
